# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
variables:
  azureServiceConnection: 'Dev(285ec89b-c6b0-46a6-9758-a0bce37bd2da)'
  storageAccount: 'musicvideobuilder'
  appName: 'music-video-builder'
  zoneId: '38cb0269f6c3c468bc32f17fc465e647'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.9.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@16.2.10
    npm install
    ng build
  displayName: 'npm install and build'

- task: AzureKeyVault@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    KeyVaultName: musicvideobuilder
    SecretsFilter: 'CloudFlareCacheToken,StaticWebAppDeploymentToken'
    RunAsPreJob: false
- task: AzureStaticWebApp@0
  inputs:
    app_location: '/dist/$(appName)'
    api_location: 'api'
    output_location: '$(Build.Repository.LocalPath)/dist/$(appName)'
    config_file_location: '/dist/$(appName)/assets'
    azure_static_web_apps_api_token: $(StaticWebAppDeploymentToken)    
- task: PowerShell@2
  displayName: 'Clear Cloudflare Cache'
  inputs:
    filePath: 'cacheClear.ps1'
    arguments: >
      -ZoneId $(zoneId)
      -ApiToken $(CloudFlareCacheToken) 
      -FileLocation '$(Build.Repository.LocalPath)/dist/$(appName)'


