# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
variables:
  azureServiceConnection: 'Dev(285ec89b-c6b0-46a6-9758-a0bce37bd2da)'
  storageAccount: 'musicvideobuilderpublic'
  appName: 'music-video-builder'
  zoneId: '38cb0269f6c3c468bc32f17fc465e647'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build
  displayName: 'npm install and build'
- task: AzureCLI@2
  displayName: 'Clear Static website'
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob delete-batch --account-name $(storageAccount) --source "\$web"'
- task: AzureCLI@2
  displayName: 'Upload new Static Website'
  inputs:
    azureSubscription: $(azureServiceConnection)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload-batch --account-name $(storageAccount) --destination "\$web" --source ''$(Build.Repository.LocalPath)/dist/$(appName)'''
- task: AzureKeyVault@2
  inputs:
    azureSubscription: $(azureServiceConnection)
    KeyVaultName: musicvideobuilder
    SecretsFilter: 'CloudFlareCacheToken'
    RunAsPreJob: false
- task: PowerShell@2
  displayName: 'Clear Cloudflare Cache'
  inputs:
    filePath: 'cacheClear.ps1'
    arguments: >
      -ZoneId $(zoneId)
      -ApiToken $(CloudFlareCacheToken) 
      -FileLocation '$(Build.Repository.LocalPath)/dist/$(appName)'
